export const ActionTypes = {
  UPDATE_PRODUCT_LIST: "UPDATE_PRODUCT_LIST",
  SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",
  UPDATE_A_PRODUCT: "UPDATE_A_PRODUCT",
  DELETE_A_PRODUCT: "DELETE_A_PRODUCT",
  UPDATE_LOADER: "UPDATE_LOADER",
};
